export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Questions} from './Questions'
export {default as Question} from './Question'
export {default as Result} from './Result'